### ISSUE TITLE
Make pip installable?

### ISSUE THREAD

**Issue by jo-mueller** [juglab/pn2v#10]
Dear n2v developers,

I've only disovered this repo recently and already use it quite a bit. Especially the torch implementation of the n2v is a huuuuge plus for me. Is there a chance to make this repo pip -installable? At a glance, all it lacks is a `setup.py`/`setup.cfg` file, does it?

Best, Johannes

**Comment by jdeschamps** [comment]
Done in https://github.com/juglab/pn2v/pull/13

Thanks for the suggestion!
